Repository SRM-IST-KTR/gcsrm_server, pull requests merged in 2025-10, with the labels that each got.

#39 Enhance Swagger documentation and improve helmet configuration for security
  src/app.js
  src/routes/team.route.js
  src/utils/swagger.js
  vercel.json
Labels: documentation, hacktoberfest

#41 Update Hacktoberfest guidelines and validation criteria
  .github/pull_request_template.md
  CONTRIBUTING.md
  HACKTOBERFEST_GUIDE.md
  HACKTOBERFEST_SETUP.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#43 Update Swagger UI setup to use CDN assets directly
  src/app.js
  src/utils/swagger.js
  vercel.json
Labels: bug, hacktoberfest, hacktoberfest-accepted

#25 event tasks
  package-lock.json
  src/app.js
  src/controller/event.controller.js
  src/models/event.model.js
  src/routes/event.route.js
  src/routes/index.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
